# Dockerfile.mysql

FROM mysql:latest

# Copier le script SQL d'initialisation dans le répertoire d'initialisation
COPY ./backend/quizz.sql /docker-entrypoint-initdb.d/

# Définir les variables d'environnement
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=asteriaQuizz
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root
