# docker-compose.dev.yml

version: '3'

services:

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asteriaQuizz
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend:
    build:
      context: ./  # Modification du chemin du contexte
      dockerfile: ./docker/backend/Dockerfile  # Correction du chemin du Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/app # Montez le répertoire du backend pour permettre les mises à jour en temps réel
      - /usr/app/node_modules # Volume anonyme pour node_modules seulement
    environment:
      NODE_ENV: development
      DATABASE_HOST: mysql-db  # Utilisez le nom du service MySQL comme hôte
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE: asteriaQuizz
      
  frontend:
    build:
      context: ./  # Modification du chemin du contexte
      dockerfile: ./docker/frontend/Dockerfile  # Correction du chemin du Dockerfile
    ports:
      - "8880:80"
    volumes:
      - ./frontend:/usr/app # Montez le répertoire du frontend pour permettre les mises à jour en temps réel
    environment:
      NODE_ENV: development # Définissez l'environnement sur le mode développement
