version: '3'

services:

  asteriadatabase:
    container_name: asteriadatabase
    image: postgres:15.3
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./.env
    environment:
      PGDATA: /var/lib/postgresql/data/asteria/
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - asteriadata:/var/lib/postgresql/data/
    networks:
      - netasteria

  backend:
    build:
      context: ./ 
      dockerfile: ./docker/backend/Dockerfile  
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    env_file: ./.env
    environment:
      DATABASE_HOST: asteriadatabase
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE: ${DATABASE_NAME}
    networks:
      - netasteria
    depends_on:
      - asteriadatabase

  frontend:
    build:
      context: ./  
      dockerfile: ./docker/frontend/Dockerfile  
    ports:
      - "8880:80"
    volumes:
      - ./frontend:/usr/app
    environment:
      NODE_ENV: development
    networks:
      - netasteria

volumes:
  asteriadata:
networks:
  netasteria:
    name: netasteria
    external: true
